### ISSUE TITLE
The ability to define menus and allow staff to place orders on holidays (both official and weekends) through user groups

### ISSUE THREAD

**Issue by daway0** [daway0/pors#185]

**Comment by ArCaneSec** [comment]
@daway0 
After implementing this, how are we going to send email reminders for users? since users can now be in different groups, some of them can order in holidays, while some of them cant, do we have to calculate deadline for both types and send different reminders?

**Comment by daway0** [comment]
admin panel icon must be in portal, for admins 
+
auto login

**Comment by daway0** [comment]
To use this feature, a group with the code ‍`ORDER_IN_HOLIDAY‍` must be created. The admin can assign users to groups through the Django admin panel.

Currently, the ability to define a group for the admin has been disabled for me through the Django admin panel.

**Comment by daway0** [comment]
@ArCaneSec 
The values for `openForLaunch` and `openForBreakfast` return `false` on holidays, which results in items not being displayed in the menu.

**Comment by daway0** [comment]
Weekend holidays should also be added to the system through the `pors_holiday` table. Additionally, their deadlines should be set just like regular days.
